version: '3'

services:
  nodejs-app:
    build: .
    ports:
      - "80:80" 
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: abcDatabase
      POSTGRES_USER: abc
      POSTGRES_PASSWORD: abc_PASSWORD
    ports:
      - "5432:5432"



